// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "sudhanv09/torus/view/components"

func CalendarPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"layout\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Sidebar("calendar").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"layout__main\"><header class=\"header\"><div class=\"header__content\"><div style=\"display: flex; align-items: center; justify-content: space-between;\"><div><h1 style=\"font-size: 1.875rem; font-weight: 700; margin-bottom: var(--space-xs);\">Calendar</h1><p style=\"color: var(--text-muted);\">Upcoming releases and air dates</p></div><div style=\"display: flex; gap: var(--space-sm); align-items: center;\"><button class=\"btn\" style=\"padding: var(--space-md); background: var(--surface); border: 1px solid var(--border);\"><span class=\"material-symbols-outlined\">chevron_left</span></button> <span style=\"font-weight: 600; min-width: 10rem; text-align: center;\">October 2023</span> <button class=\"btn\" style=\"padding: var(--space-md); background: var(--surface); border: 1px solid var(--border);\"><span class=\"material-symbols-outlined\">chevron_right</span></button></div></div></div></header><main class=\"content\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Calendar(getSampleCalendarDays()).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</main></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout("Torus - Calendar").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func getSampleCalendarDays() []components.CalendarDay {
	return []components.CalendarDay{
		// Week 1
		{Number: 24, OtherMonth: true, Events: []components.CalendarEvent{}},
		{Number: 25, Events: []components.CalendarEvent{}},
		{Number: 26, Events: []components.CalendarEvent{}},
		{Number: 27, Events: []components.CalendarEvent{}},
		{Number: 28, Events: []components.CalendarEvent{}},
		{Number: 29, Events: []components.CalendarEvent{}},
		{Number: 30, Events: []components.CalendarEvent{}},
		// Week 2
		{Number: 1, Events: []components.CalendarEvent{}},
		{Number: 2, Events: []components.CalendarEvent{
			{Title: "Ahsoka S01E08", Type: "show"},
		}},
		{Number: 3, Events: []components.CalendarEvent{}},
		{Number: 4, Events: []components.CalendarEvent{
			{Title: "The Creator", Type: "movie"},
		}},
		{Number: 5, IsToday: true, Events: []components.CalendarEvent{
			{Title: "Loki S02E01", Type: "show"},
			{Title: "Our Flag Means...", Type: "show"},
		}},
		{Number: 6, Events: []components.CalendarEvent{
			{Title: "Gen V S01E04", Type: "show"},
		}},
		{Number: 7, Events: []components.CalendarEvent{}},
		// Week 3
		{Number: 8, Events: []components.CalendarEvent{}},
		{Number: 9, Events: []components.CalendarEvent{}},
		{Number: 10, Events: []components.CalendarEvent{}},
		{Number: 11, Events: []components.CalendarEvent{}},
		{Number: 12, Events: []components.CalendarEvent{
			{Title: "Loki S02E02", Type: "show"},
		}},
		{Number: 13, Events: []components.CalendarEvent{
			{Title: "Taylor Swift ...", Type: "movie"},
		}},
		{Number: 14, Events: []components.CalendarEvent{}},
		// Week 4
		{Number: 15, Events: []components.CalendarEvent{
			{Title: "Rick and Mor...", Type: "show"},
		}},
		{Number: 16, Events: []components.CalendarEvent{}},
		{Number: 17, Events: []components.CalendarEvent{}},
		{Number: 18, Events: []components.CalendarEvent{}},
		{Number: 19, Events: []components.CalendarEvent{
			{Title: "Loki S02E03", Type: "show"},
		}},
		{Number: 20, Events: []components.CalendarEvent{
			{Title: "Killers of the ...", Type: "movie"},
		}},
		{Number: 21, Events: []components.CalendarEvent{}},
		// Week 5
		{Number: 22, Events: []components.CalendarEvent{
			{Title: "Rick and Mor...", Type: "show"},
		}},
		{Number: 23, Events: []components.CalendarEvent{}},
		{Number: 24, Events: []components.CalendarEvent{}},
		{Number: 25, Events: []components.CalendarEvent{}},
		{Number: 26, Events: []components.CalendarEvent{
			{Title: "Loki S02E04", Type: "show"},
		}},
		{Number: 27, Events: []components.CalendarEvent{
			{Title: "Five Nights a...", Type: "movie"},
		}},
		{Number: 28, Events: []components.CalendarEvent{}},
		// Week 6
		{Number: 29, Events: []components.CalendarEvent{
			{Title: "Rick and Mor...", Type: "show"},
		}},
		{Number: 30, Events: []components.CalendarEvent{}},
		{Number: 31, Events: []components.CalendarEvent{}},
		{Number: 1, OtherMonth: true, Events: []components.CalendarEvent{}},
		{Number: 2, OtherMonth: true, Events: []components.CalendarEvent{}},
		{Number: 3, OtherMonth: true, Events: []components.CalendarEvent{}},
		{Number: 4, OtherMonth: true, Events: []components.CalendarEvent{}},
	}
}

var _ = templruntime.GeneratedTemplate
